spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:${user.dir}/filesystem/filenodes/kift
    username: root
    password: 301537gY
logging:
  level:
    root: info
#    org.hyperledger: debug
